apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: praveenraj29/fastapi-hello-world:8-289b564d6f2dbec4ca0f114d90ae04a64874fe5e
        ports:
        - containerPort: 8000
