apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: praveenraj29/fastapi-hello-world:18-87f66998702db749a31a0c2a1eb9b20b589ed668
        ports:
        - containerPort: 8000
