apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: praveenraj29/fastapi-hello-world:10-6251232e2b021f4ca16e9438527de8fddc70da0b
        ports:
        - containerPort: 8000
